"""empty message

Revision ID: d0b80450033d
Revises: 959c5ab9dcc1
Create Date: 2019-05-15 15:36:59.154001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0b80450033d'
down_revision = '959c5ab9dcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_problem', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('bbs_problem_ibfk_1', 'bbs_problem', type_='foreignkey')
    op.create_foreign_key(None, 'bbs_problem', 'bbs_users', ['user_id'], ['id'])
    op.drop_column('bbs_problem', 'user')
    op.add_column('bbs_solve', sa.Column('problem_id', sa.Integer(), nullable=False))
    op.add_column('bbs_solve', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('bbs_solve_ibfk_2', 'bbs_solve', type_='foreignkey')
    op.drop_constraint('bbs_solve_ibfk_1', 'bbs_solve', type_='foreignkey')
    op.create_foreign_key(None, 'bbs_solve', 'bbs_users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bbs_solve', 'bbs_problem', ['problem_id'], ['id'])
    op.drop_column('bbs_solve', 'user')
    op.drop_column('bbs_solve', 'problem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_solve', sa.Column('problem', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bbs_solve', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bbs_solve', type_='foreignkey')
    op.drop_constraint(None, 'bbs_solve', type_='foreignkey')
    op.create_foreign_key('bbs_solve_ibfk_1', 'bbs_solve', 'bbs_problem', ['problem'], ['id'])
    op.create_foreign_key('bbs_solve_ibfk_2', 'bbs_solve', 'bbs_users', ['user'], ['id'])
    op.drop_column('bbs_solve', 'user_id')
    op.drop_column('bbs_solve', 'problem_id')
    op.add_column('bbs_problem', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bbs_problem', type_='foreignkey')
    op.create_foreign_key('bbs_problem_ibfk_1', 'bbs_problem', 'bbs_users', ['user'], ['id'])
    op.drop_column('bbs_problem', 'user_id')
    # ### end Alembic commands ###
